### PR TITLE
Project status

### LINKED ISSUE #12: Project Status
A **big** part of each project page should be its current status. We want people to at least know whether or not a project is still running if they have a link from 3 weeks ago.

This could be as easy as current: {true, false}, up to status: {planning, build, demonstration}, and as complicated as a new layout for complete projects that looks more like a photos-with-captions instead of question-and-answer.

### PR DESCRIPTION
**Pull request by taylortrimble**
Changes:
- If a project has it's `conclusion_post` key set, it is considered a past project
  - It does not appear on the front page
  - It redirects to the value of `conclusion_post`
- The projects_controller has been updated to parse all projects into the correct current, past, and all categories. This is done on load so we are never conditionally testing on each page load. This should be great for our not-changing-much project data

Closes #12.

### CODE REVIEW

**Comment by taylortrimble** [comment]
I also put fixes for #79 here.

**Comment by mplewis** [comment]
Past projects show up under the Show All Projects fold, right?

I don't really have a way to test this yet.

**Comment by taylortrimble** [comment]
If you add `"conclusion_post": ""` to a few projects you'll see it

**Comment by mplewis** [comment]
Can we consider changing a check for key existence for a `"conclusion_post": true` check?

**Comment by taylortrimble** [comment]
Thought about it. So you could have:

```
"conclusion_post": "true",
"conclusion_post_link": "news.teslaworks.net/2013/01/01/its_done/"
```

and

```
"conclusion_post": "false",
"conclusion_post_link": ""
```

instead of the key existing/not existing?

**Comment by mplewis** [comment]
Nope, not `"true"`, just `true`. Boolean is a JSON type!

**Comment by taylortrimble** [comment]
But that idea?

**Comment by mplewis** [comment]
Yeah, sounds good to me! :snake:

**Comment by taylortrimble** [comment]
Just to be sure: you **dont** want to use key indication to replace that true/false? That would result in congruent keys for all projects, at the expense of more of them.

That would probably have debugging-is-nice implications that outweigh the extra file size which doesn't matter since we cache it. Only downsides: if that changes later.

**Comment by mplewis** [comment]
Eh, I'm OK either way honestly. I actually do like using key indication, on second thought! Just as long as we use `true` instead of `""` for self-documenting sake.

**Comment by taylortrimble** [comment]
Oh, I see. On a finished project though that won't actually be empty (we hope). Because it should point to a blog post about the finished project.

**Pull request merged**
