### PR TITLE
Doctor for docker

### PR DESCRIPTION
**Pull request by taylortrimble**
This containerizes our actual app, devoid of any configuration and data.

The idea is that **GitHub holds a version history of the empty website**, and **Docker holds a version history of the running image** (with commit history of source, data, databases, and configuration).

For an imaginary third party _only using_ our website, they can do this:
1. `docker pull` to get our blank website, auto-built from the commit hook we'll set up
2. Run the site with `docker run -d -p 80:80 teslaworksumn/teslaworks.net /root/run.sh`
   - This hopefully generates a lot of data we don't want to lose!
3. Update the site by:
   1. Committing the current version of the app `docker commit $RUNNING_CONTAINER_ID teslaworksumn/teslaworks.net:staging`
   2. Updating the resulting image, which provides a new container for testing: `docker run teslaworksumn/teslaworks.net:staging /root/update.sh`
   3. After testing, commit the container to become the new latest version of the site: `docker commit $TESTING_CONTAINER_ID teslaworksumn/teslaworks.net`

If anything goes wrong later, we can revert to a prior image by inspecting `docker history teslaworksumn/teslaworks.net` and picking a good prior working image. We can also push to remote Docker image repository for backing up the full image of our site, ready to run, with real production data and everything!

### CODE REVIEW

**Comment by mplewis** [comment]
Into where does our API data (config.py) fall? Logic repo or private config repo?

I ask because it feels weird bundling private API keys with public website source (project JSON).

**Comment by taylortrimble** [comment]
`sample_config.py` is copied on `docker_build` to a location outside the image’s repo directory (since that gets updated) and is sourced from there. So updates to it only happen on the docker repo.

Resultingly, our private config could go away if we wanted it to. We’d just update the files initially, and we get to keep that data as we update the site.

**Comment by taylortrimble** [comment]
There are a couple small issues with this, but no new ones from what we have now! :grin:
- pip warnings
- running UWSGI as root

This presently assumes you copy `config/sample_config.py` to `config/twnet_config.py` before you `docker build`. We can change that later, but if you're okay with this @mplewis we can merge now!

**Comment by taylortrimble** [comment]
I'm not a fan of putting the Dockerfile inside teslaworksumn/teslaworks.net anymore. :bomb:

**Pull request closed without merging**
