### PR TITLE
Take out those needs. Aren't worth displaying now.

### PR DESCRIPTION
**Pull request by taylortrimble**
@mplewis Just a hot fix to get rid of those embarrassingly empty/malformatted project needs

### CODE REVIEW

**Comment by mplewis** [comment]
Consider doing this with the Postgres move? I have a migration script that ignores need categories.

**Comment by taylortrimble** [comment]
We can take out the data separately: I just want to get it looking good for the immediate visitors

**Comment by mplewis** [comment]
:snake:

**Comment by taylortrimble** [comment]
:baby:

**Pull request merged**
