### PR TITLE
Cache JSON

### PR DESCRIPTION
**Pull request by taylortrimble**
I decided to create a `ProjectsController` class that we interface with projects through.

In its current iteration, all project data is lazy-loaded. We assume that we are the only ones writing data, and therefore do not check for changed files when "getting".

### CODE REVIEW

**Comment by taylortrimble** [comment]
When running tests, this will write compressed JSON, so be sure to revert it if you want to keep the tree's copy pretty.

Good to go, @mplewis?

**Comment by mplewis** [comment]
Looks great to me!

If you were wondering about pretty-printing JSON, may I suggest adding a debug keyword argument that toggles indent on the JSON writer like so:

``` python
>>> import json
>>> print json.dumps({'4': 5, '6': 7}, sort_keys=True,
...                  indent=4, separators=(',', ': '))
{
    "4": 5,
    "6": 7
}
```

**Comment by taylortrimble** [comment]
I put that in for a while, but it still clobbers the order of the file yet anyway. That made me decide we might as well just have it compressed in production anyway and just revert updates to keep it pretty as long as we want it to be.

**Comment by mplewis** [comment]
Perhaps we should just start using JSON editors instead of editing the JSON by hand. It'd be safer for the code anyway.

I found http://jsoneditor.appspot.com/ which seems nice.

Anyway, this set of features looks good -- merge at will!

**Pull request merged**
