### PR TITLE
Initial easy routes

### LINKED ISSUE #9: Add app routes
I think that our URL structure just gets to be as simple as our site is.
- `/` is just the home page
- `/blog` goes to our blog
- `/<project_name>` goes to the project

No projects named "blog".

Th-th-th-th-that's all folks! :pig: Whaddaya think?

### PR DESCRIPTION
**Pull request by taylortrimble**
All right! I'm not thinking this is ready yet, but here's my start. More to think about:
- [x] Projects that don't match should return a 404

Closes #9 when pulled.

### CODE REVIEW

**Comment by taylortrimble** [comment]
@mplewis This is ready for you to look at.

**Comment by mplewis** [comment]
Looks solid to me. The only nitpicky thing I have to mention is that I still like the JSON nested as such:

```
"photos": {
    <front page photo>: <url>
    <other photos>: [<array of urls>]
}
```

This is the form I've seen most other sites use -- nesting and using JSON in a hierarchical manner is great IMO because it keeps the code organized.

Take a look at, say, [Last.fm's JSON](http://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&user=rj&api_key=5c14ae46a8579d7c453edf696ce5efed&format=json) in the [JSON Editor Online](http://www.jsoneditoronline.org/).

**Comment by taylortrimble** [comment]
I like that a lot better too, I couldn't get Python to parse it, and it failed any JSON linter I threw it at. Are you sure that isn't a non-standard extension?

If you can get it to work, then we can go with it.

**Comment by mplewis** [comment]
I just tested `lightshow.json` in JSON Editor Online. Looks good to me. The rest of everything looks good to me too.

Merge to confirm!

**Comment by mplewis** [comment]
Ooh, that looks interesting. I'll redo my thingy.

**Comment by taylortrimble** [comment]
(Slower on the merges please)

**Comment by mplewis** [comment]
I know what happened with merges -- before making this pull request, I had a typo fix commit that I merged to master (commit 495e71c).

Didn't realize that old commits would mess with current pull requests. Sorry about the trouble.

**Comment by taylortrimble** [comment]
Easy future fix - one committer per PR. Just branch off of my PR and then PR into my PR. Lol, it works. :)

**Comment by mplewis** [comment]
That makes sense! I'll do that next time, thanks.

**Comment by mplewis** [comment]
Also. Look good to you? Once you think it looks good I'll clean up the tree.

**Comment by taylortrimble** [comment]
Manually merged! Thanks @mplewis.

**Pull request merged**
