### PR TITLE
Implement Octopress

### PR DESCRIPTION
**Pull request by mplewis**
Title says it all. I recommend using RVM for the Ruby install and stuff.

I added a little script to deploy Octopress. Run it from the server root or ~~bad things~~ nothing happens.

I've also installed a Bootstrap theme. For your pleasure.

### CODE REVIEW

**Comment by mplewis** [comment]
paging @tylrtrmbl

**Comment by taylortrimble** [comment]
I didn't get this to deploy on my system.

```
(twnet)taylor:teslaworks.net % python deploy_octopress.py 
rake aborted!
Could not find rake-0.9.2.2 in any of the sources

(See full trace by running task with --trace)
Non-zero exit status. Something went wrong. Exception is below.

Traceback (most recent call last):
  File "deploy_octopress.py", line 17, in <module>
    rake_results = deploy_octopress()
  File "deploy_octopress.py", line 12, in deploy_octopress
    rake_output = subprocess.check_output(['rake', 'generate'])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 544, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['rake', 'generate']' returned non-zero exit status 1
(twnet)taylor:teslaworks.net % rake generate
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

(See full trace by running task with --trace)
(twnet)taylor:teslaworks.net % rake --version
rake, version 0.9.2.2
```

I am using rvm to install my rubies. I appear to have an A-OK version of rake (`rake --version` returns `rake, version 0.9.2.2`) but the deploy script doesn't find it.

Does it find it on yours?

Also, you'll note that without a `Rakefile` the rake command doesn't work anyway.

I feel like I am missing something.

**Comment by taylortrimble** [comment]
Using this interpretation of

> Run it from the server root

```
(twnet)taylor:/ % python ~/projects/teslaworks/teslaworks.net/deploy_octopress.py 
Traceback (most recent call last):
  File "/Users/taylor/projects/teslaworks/teslaworks.net/deploy_octopress.py", line 17, in <module>
    rake_results = deploy_octopress()
  File "/Users/taylor/projects/teslaworks/teslaworks.net/deploy_octopress.py", line 10, in deploy_octopress
    os.chdir(OCTOPRESS_DIR)
OSError: [Errno 2] No such file or directory: 'octopress'
```

I get that error, additionally.

**Comment by mplewis** [comment]
Your first try was correct. Run it inside the root of the git repo folder.

Can you run `rake generate` inside `/octopress` just fine?

**Comment by taylortrimble** [comment]
> Can you run rake generate inside /octopress just fine?

No – and the answer why is interesting. My rvm was set up to use version 1.9.3 with my own `twnet` gemset (1.9.3@twnet). When inside the `/octopress` directory the `.rvmrc` specified the global gemset (1.9.3, no `@` sign). Anywhere outside that dir, however, the `twnet` gemset was used.

Since I had to call from route, and rake runs inside `/octopress`, the gemsets could never match (having the same gems is not sufficient) so it could never find `rake`.

Solution??: remove the `.rvmrc` file and configure rvm to use a default gemset (such as 1.9.3@myspecialgemset) on the server and our dev machines. That gemset should contain the gems we want for octopress.

**Comment by taylortrimble** [comment]
It works on your machine because your default gemset happened to be `/octopress`'s as well. Another solution (to force a certain gemset for the blog but not _all_ other ruby software on the server) is to move the .rvmrc to the git root instead of inside `/octopress`.

I'll let you decide what you like.

**Comment by taylortrimble** [comment]
Still don't pull this yet: I want to look at this some more.

**Comment by mplewis** [comment]
Thank you for doing the research on this! I felt like RVM was too good to be true in some respects. Thanks for working out some of these kinks.

I'm not sure if I understand what's up and I'll have to read your explanation again, but does running `bundle install` in the Octodirectory get the gems you need?

This ties into #6, tagging it.

**Comment by taylortrimble** [comment]
Since the gemsets don't match, running `bundle install` inside the Octodirectory (nice) installs things into the global gemset, which isn't available from git root - unless you super magically are using that gemset anyway for the git root directory too (you were, I wasn't).

To simplify, fix options are:
1. Move (or copy, to be safe) the `.rvmrc` file into the git root (where we call `deploy_octopress.py`)
2. Get rid of `.rvmrc` files altogether – just specify whatever gemset we want, and be sure that is loaded on production servers (it would crash anyway if it wasn't, so we'd know)

**Comment by mplewis** [comment]
I feel like Option 1 is a better one if someday we want to make this project `git clone` and `python setup_the_deployan.py`able for future users if/when we open-source it. Unless there's a better way to automate gemset installations.

**Comment by taylortrimble** [comment]
Solution: inside the setup-to-deploy script (which is what your `setup_the_deployan.py` script is, I presumed) we copy the `.rvmrc` file over from there.

The `.rvmrc` file is from Octopress (I thought you had made it) and it needs to be the same, so to stay compatible with Octopress updates I think that's our best route. Don't forget to `.gitignore` it so it doesn't get committed!

**Comment by taylortrimble** [comment]
OR just run the `.rvmrc` file directly. It is a bash script after all, so we could simply execute it with `bash -s octopress/.rvmrc` I _think_. But some solution like that is my favorite.

**Comment by taylortrimble** [comment]
Okay, so after looking through all this I have lots of thoughts:
1. We're literally duplicating the Octopress code. 15,000+ lines of it. I'd rather we `git clone`d and applied small patches to change what we need, all in a script. We can keep our own fork of the Octopress code so it stays stable. But for the love of god we should keep it separate! I hate having a code base with another repo just mixed in it. Plus, it makes Octopress unbearable to update if we don't.
2. I think this is a dud route anyways. Looking at a screenshot of my first deploy, I think it's going to be a **lot** of work to get the blog themed in a way that matches the rest of the site. We'd have to plop down code from our main app into the Octopress side of things, and it gets messy that way.

@mplewis, you talked to me earlier about just making our own templates by parsing markdown. I think we should start looking that route again. It will be a lot more modular and baked into the Python app.

An even better approach we can go to is this: simply supply textboxes for headings and paragraph body for specific templates. For example, say for a "project success" template, we could include a headline, a body, up to 3 photos with (longer) captions off to the side, and links at the bottom. Then the user just has to fill out textboxes for each content type.

What do you think?

Reference screenshot: 
screen shot 2013-06-18 at 8 53 40 pm

**Comment by taylortrimble** [comment]
#### Side to Side Hacking

I think we'll have to do really nasty things with the theming here, where if we change layouts in the main site (like add a footer) they won't be reflected in the blog. We'd have to do "side to side" fixes (where we have to make the update twice) or some other horrible hacking where we auto-update the blogs static content or something equally awful.

I'm sensing a good idea and slick, nice looking technology – that will turn into a nightmare. I love the Octopress stuff. I don't love it enough.

**Comment by mplewis** [comment]
After a day of hacking routes, I'm down for this.

Let's start a blog layout thread in which we discuss the infrastructure of the new blog.

Also, in all honesty, this approach really is shoehorning it all together. Ruby framework on Flask and pushing routes to make URLs pretty == not fun imo.

**Comment by taylortrimble** [comment]
Sounds good to me. At least I know what I want to use for my own blog now anyway.

**Pull request closed without merging**
