### PR TITLE
Add industry-standard graphics to help focus on photographic intent.

### PR DESCRIPTION
**Pull request by taylortrimble**
This is a running inside joke with Tesla Works placeholder images. :wink:

### CODE REVIEW

**Comment by taylortrimble** [comment]
And also gives you the change to play with GitHub's amazing image diff tools!

**Comment by mplewis** [comment]
That's pretty cool! Nice work. :+1:

**Comment by taylortrimble** [comment]
Lol. Merge if you want to. Otherwise, it's in the tree and that's all I wanted. :)

**Comment by mplewis** [comment]
it is done!

**Pull request merged**
