### PR TITLE
Basic Front Page Template

### PR DESCRIPTION
**Pull request by taylortrimble**
### Highlights
- Tesla Works at the top
- Very short (less than a sentence) tagline
- Instructions to click on the projects below to get involved
- "Filters" to highlight the most relevant projects
- Project tiles in rows with 3 elements
- Instructions on other ways to get involved, including "stop by", "email us", and "sign up for our mailing list"
- Guided FAQs to address common concerns
### Example Tagline

Be a part of amazing, student-led engineering and design projects
### Note:
- Projects are surrounded by ways to get involved, and should highlight on mouse-over
- Filters are additive. If a student is interested in MechE and EE, both kinds of projects should be highlighted.
- Lower Instructions on how to join should expand. Default text like "Looking for other ways to get involved?" with an expansion arrow
- Guided FAQs may just be called "Common Concerns" (or something better that doesn't sound concerning but isn't FAQ style)

### CODE REVIEW

**Comment by taylortrimble** [comment]
Hey @mplewis! One part of this that I am putting off implementing is the starring function of the front page, where selecting project category buttons results in projects that relate to that category being starred. More specs and info:
- Bootstrap buttons don't come with a toggle functionality by default, and switches are bad for this. Maybe checkboxes are okay... but buttons! I've thought about adding a check mark Font-Awesome icon in the button toggles state, or just making the text glow.
- I'd love to do this with our own Javascript and not some lib, just to keep things small and we-know-what's-going-on, but if this is a well-solved problem we shouldn't re-invent the wheel.
- Multiple category selection allowed
- If a project is in **_any_** active category, it gets a star
- No projects disappear
- **Maybe** we could pop starred projects to the front/top as well, but that should be after we finish the rest
- Try to keep style changes out so our guaranteed conflicting merge is minimally gruesome. But keep a note of what you'd like to do, because I suck at making things pretty. Opening issues is fine.

_I will actually tackle this myself if you don't pick it up_ (understandable since you have blog, project page enhancements) but if you **do** pick it up I won't complain.

**Comment by mplewis** [comment]
Hey @tylrtrmbl! Thanks for thinking this over. Here are my thoughts!
- I think Bootstrap buttons do come with toggle functionality! Check out [the Bootstrap docs, JS side.](http://twitter.github.io/bootstrap/javascript.html#buttons).
- I did find something cool that we probably don't want to use but I still think is awesome: http://www.larentis.eu/switch/
- This definitely feels like a custom-JS problem and one that can be easily solved with, say, jQuery bindings to .click(), etc.
- How familiar are you with doing things in JS and using jQuery? _Make sure you use some kind of library like jQuery to simplify your code or you will hate yourself!_
- Multiple category OR functionality sounds great to me!
- I like the idea of reordering the list and floating starred projects to the top as they get stars.

I will most likely not pick this up due to blag stuff, but feel free to write up something!

And if you want to swap roles at all or can't tackle something, let me know -- I love the JS side too and am happy to help.

**Comment by taylortrimble** [comment]
> I think Bootstrap buttons do come with toggle functionality! Check out the Bootstrap docs, JS side..

Lol, Google search fail. Didn't even go look at the docs, but this should have probably popped up. :stuck_out_tongue: 

> I did find something cool that we probably don't want to use but I still think is awesome: http://www.larentis.eu/switch/

Found that too! Is awesome, is something we don't want to use (for this). Somewhere else, likely Fido.

> This definitely feels like a custom-JS problem and one that can be easily solved with, say, jQuery bindings to .click(), etc.

Heck to the yes!

> How familiar are you with doing things in JS and using jQuery?

Not, but desire to learn. Esp about DOM, which is what this is I think.

> Make sure you use some kind of library like jQuery to simplify your code or you will hate yourself!

JQuery it is!

> Multiple category OR functionality sounds great to me!

Yeppers!

> I like the idea of reordering the list and floating starred projects to the top as they get stars.

Animations will be hard on that, but still kewl. Will try.

> I will most likely not pick this up due to blag stuff, but feel free to write up something!
> And if you want to swap roles at all or can't tackle something, let me know -- I love the JS side too and am happy to help.

Okay, sweet, drill down time! I found a horrible JS tutorial earlier, so if you have a good tut/guide/crash-course recommendation, let me know!

**Comment by taylortrimble** [comment]
Thanks for the note about JQuery especially, I was going to try to avoid it to avoid complicating things. It's good to know that I should take the opposite course of action to accomplish that goal.

**Comment by mplewis** [comment]
It helps to try developing with and without jQuery to understand why everyone uses jQuery.

jQuery doesn't add all THAT much when it gets down to it, just some really nice ways of doing things that kind of suck to do in JS alone. [Check out these examples](http://www.sitepoint.com/jquery-vs-raw-javascript-2-css3-animation/) to see native JS vs jQuery.

I think the most important part of understanding jQuery is selectors. Take a look at [this walkthrough](http://www.netmagazine.com/tutorials/getting-most-out-jquery-selectors) and see if that helps explain anything?

Also -- animations shouldn't be too hard if we do it right, I hope! jQuery or CSS3 should be able to handle animations just fine once we get our ideas right.

**Comment by mplewis** [comment]
Also also, :+1: on animations waiting till last.

**Comment by taylortrimble** [comment]
This is ready for review from a layout/architecture/**_initial**_ styling perspective!

**Comment by taylortrimble** [comment]
@mplewis Let's merge this muther. Do you think it's ready for master, if not final viewing eyes?

**Comment by mplewis** [comment]
:tropical_drink: :tropical_fish:

**Pull request merged**
