### PR TITLE
move masthead to own file; make "active" classes smarter

### LINKED ISSUE #35: Implement nav bar with Jinja partials
Partials are awesome! And we should never, ever code a nav bar in more than once place. Introducing: [Jinja includes!](http://jinja.pocoo.org/docs/templates/#include)

Usage:

```
{% include 'header.html' %}
```

Of note:

> Included templates have access to the variables of the active context by default.

And that's all you need to know. :satisfied: Let's move the Nav bar that's currently in the project-pages to a `header.html` partial.

### PR DESCRIPTION
**Pull request by mplewis**
Closes #35.

### CODE REVIEW

**Comment by mplewis** [comment]
Add the newline and merge at will!

**Comment by taylortrimble** [comment]
So the process for making the blog tab active is to call `render_template('blog.html, blog=True)`?

We should wait to merge until we can test! I can do that in a testing branch we merge the home layout and this into.

**Comment by mplewis** [comment]
Yes.

I've informally tested it and it works, but do feel free to do so in more depth!

**Comment by taylortrimble** [comment]
I have an idea. Code forthcoming.

**Pull request closed without merging**
