### PR TITLE
Stop checking for title == 'Blog'

### LINKED ISSUE #51: Remove masthead Jinja checks for title == 'blog'
Since Flask isn't hosting a blog we don't need to check for `blog` in `title` in the template `masthead.html`.

### PR DESCRIPTION
**Pull request by taylortrimble**
It's external now! Fixes #51.

### CODE REVIEW

**Comment by mplewis** [comment]
Do we still need to change the blog link to http://teslaworks.tumblr.com/?

**Comment by taylortrimble** [comment]
I was hoping we could host/pseudo host from teslaworks.net/blog or blog.teslaworks.net like PT does!

**Comment by mplewis** [comment]
Sure thing. Let's make sure to get in touch with @bendemaree re: domain stuff. Or, whoever has access to our current domain!

:haircut:

**Comment by taylortrimble** [comment]
Are we just going to use the rso-teslaworks.sua.umn.edu page for now? I think we can change this to teslaworks.sua.umn.edu or even teslaworks.umn.edu if we ask nicely. I prefer this to .net, but we'll need to check with the Officers.

**Comment by mplewis** [comment]
Let's use `rso-teslaworks` for the tech demo and try for `teslaworks.umn.edu` once we're through this sprint!

**Pull request merged**
