### PR TITLE
Requirements file

### PR DESCRIPTION
**Pull request by bendemaree**
This adds the requirements file for `pip`.

### CODE REVIEW

**Comment by taylortrimble** [comment]
Is there a way in python to have it update on minor releases but not major ones? Or is that a rubyism?

**Comment by bendemaree** [comment]
You can always do `Flask>=0.9,<1.0`.

**Comment by taylortrimble** [comment]
Let's do that! Seems like it would be nice!

**Comment by mplewis** [comment]
Looks fantastic, thanks.

**Pull request merged**
