### PR TITLE
Really ignore .pyc files, discuss virtual environments

### PR DESCRIPTION
**Pull request by taylortrimble**
I don't think `.pyc` files were ignored correctly on my system. Also, @mplewis, do you have Flask available globally on your system? I ran mine from a virtual environment named `venv` with virtualenv and `pip install`ed flask from there.

I'm assuming a lot of people will do that, and if people with graphical git use `venv` for their virtual environment then it won't be automatically added. :grin:

### CODE REVIEW

**Comment by mplewis** [comment]
I already ignored *.pyc and pushed it, seemingly after you did yours but before you changed and pull requested it.

I don't seem to have to create a `venv` folder; I've got mine set up so that my virtual environment is named `python27` and can be found in `~/.virtualenvs/python27` and is activated with `workon python27`. We should investigate `virtualenv` more.

**Comment by taylortrimble** [comment]
I think you ignored `.pyc` vs `*.pyc` which on my system resulted in not ignoring `pyc` files. :wink: As for the other thing, I might just have to look more into how to use virtual environments. Obviously having the environment outside the repo would solve the problem of needing an ignore. Will remove.

**Comment by bendemaree** [comment]
Hey guys, hoping to provide some insight on `virtualenv`.

Y'all have probably read this, but a virtualenv contains a whole Python environment, including the Python executable and a copy of `pip`, the Python package manager (err, one of them, at any rate).

In general virtualenvs are not portable.  In some scenarios they may appear to be, but generally speaking virtualenvs are architecture-specific, and they become far more specialized when you install a Python package that compiles C extensions.

In short, they're binaries and so they probably won't be portable, and shouldn't be tracked in a VCS.

There might be a little extra confusion here; I also installed, fixed, and reinstalled `virtualenvwrapper` which is a suite of convenience shell commands for working with virtualenvs.  It enables `mkvirtualenv`, `workon`, `deactivate`, `rmvirtualenv` etc.  This is installed system-wide but you'll need to include the wrapper in your `.bashrc` or `.zshrc` or what have you.  Documentation [here](http://virtualenvwrapper.readthedocs.org/en/latest/index.html), but looks like this:

```
export WORKON_HOME=$HOME/.venvs
export PROJECT_HOME=$HOME/projects
source /usr/local/bin/virtualenvwrapper.sh
```

A few other notes:
- I'm extremely tempted to make the system Python 2.7 and save us a bunch of trouble down the road.
- If you've installed packages to the system site (I see blinker and a few others) you can remove those.
- Generally you want to create your virtualenv and name it with the project name, i.e. "teslaworks" vs. a more generic name.  Virtualenvs are cheap and you can make one for every project.

Hope this helps a bit.  Sorry if I went overboard.  Virtualenvs are a tool deeply embedded in my workflow now and I get excited about them...

**Comment by taylortrimble** [comment]
@bendemaree **Thank you!** I did find a lot of this out yesterday from breadcrumbs, but I'm glad you took the time to write it down here for future use! Because I'll even forget myself.

I'm not sure what this means (I am n00bly):

> - I'm extremely tempted to make the system Python 2.7 and save us a bunch of trouble down the road.

And I'll be sure to use a project virtualenv! I think I'm using `twnet` on my own machine but I'll see what it is if I start working on the server.

**Comment by bendemaree** [comment]
You're far from n00bly...

The system Python is what I mean by just typing in `python` in your shell of choice; it's 2.6 right now and @mplewis installed 2.7 as well but it's not the default.  I believe there are a few packages out there that we may desire to use that don't support 2.6.

You're welcome to make it your own on the server as well; I'll have my own in my home folder.  Ideally we'd have a requirements file that we could pass to `pip` that would allow you to have a pristine virtualenv in minutes anytime you make a new one.  I'm issuing a PR shortly...  :-)

**Comment by taylortrimble** [comment]
rawsome! Also, yep 2.7 it is then!

**Pull request merged**
