### PR TITLE
Make teslaworks.net deployable with pip

### LINKED ISSUE #6: Deployable
Hey @mplewis or @bendemaree! I'd like for this to be deployable to teslaworks-rso.sua.umn.edu because we might as well start on that now.

With a README description? Anyone want to tackle? One-liner deploys are fun too.

### PR DESCRIPTION
**Pull request by mplewis**
Closes #6.

### CODE REVIEW

**Comment by mplewis** [comment]
Let's freeze reqs by changing `>=` to `==`. Never know when stuff could change.

**Comment by taylortrimble** [comment]
I'd prefer to use the ranges if they're using semantic versioning, since they promise not to break compatibility for minor/sub version bumps. But it's probably not worth checking if each project abides by that, so `==` is fine too.

**Comment by mplewis** [comment]
Check this out: http://www.pip-installer.org/en/latest/requirements.html

They are vague about what to do but they do note you _might_ have more problems with `>=` vs `==`. I couldn't find anything about minor version number changes, but let's go the safe route for now. Yaythanks :dancer:

**Comment by taylortrimble** [comment]
I just added deploy notes to the wiki and README. We should keep these up to date as we move on! #39

**Pull request merged**
