### PR TITLE
Change id to be consistent with postgres cols

### PR DESCRIPTION
**Pull request by mplewis**
Just as requested, @tylrtrmbl

### CODE REVIEW

**Comment by taylortrimble** [comment]
Actually there's one more piece of this! The reason for making them consistent was so that we could interpolate it into the query string with the `', '.join(ARRAY)` thingy.

`GET_PROJECTS_QUERY = 'SELECT %s FROM projects ORDER BY display_order;' % ', '.join(PROJECTS_KEY_ORDER)`

**Comment by taylortrimble** [comment]
Extended reasoning: I like that we don't have to maintain manual consistency if we do it that way.

**Comment by mplewis** [comment]
String interpolation is Bad News Bears when you're talking queries. I refuse to interpolate. I'm OK with this if we can find a safe way to do it.

**Comment by taylortrimble** [comment]
I think since it's only interpolating hard coded, opposed to user values, we're probably ok.

I'm not even usually a fan of it either even for hard coded, but the redundancy issue is another bad news bears when we add columns and start getting bounds exceptions because we didn't update N | N > 1 places.

C'moooooon! :wink:

**Comment by mplewis** [comment]
I think it's baaaad. I don't want to include _any_ risk of SQL injection.

Here's a scenario in which this could be bad:
- We deploy with the live Flask debugger on by mistake
- Bad user gets access to a console on a 503
- Bad user replaces a value in `PROJECTS_KEY_ORDER` with `; DROP TABLES everything_taylor_loves`

I think we should just be including a note saying to update column names when you update the column name array and vice versa.

**Comment by taylortrimble** [comment]
Couldnt they just replace the query string too then? ;)

I'm not buying a real security risk here, but am willing to relent.

**Comment by mplewis** [comment]
I suppose they could, now that you mention it.

Still, I'm afraid of code smells just as much as warnings and errors. And I
think maintaining two sets of keys in contiguous lines isn't that big a
price to pay to keep our code nice. Is that fair?

**Comment by mplewis** [comment]
p.s. No real security risk right now. Security risk if dumb devs start
doing dumb things. (:

**Comment by taylortrimble** [comment]
I think the codesmell _is_ having to maintain manual consistency - I'll give you final call.

**Comment by mplewis** [comment]
Let's do it your way. I'll make things verbose and finish the PR.

**Comment by mplewis** [comment]
This is actually really really awful IMHO. Are you sure you wanna go ahead with this?

**Comment by taylortrimble** [comment]
Naw, not necessary

**Comment by mplewis** [comment]
REVERTED. Merging now

**Comment by mplewis** [comment]
uggghh my brain

**Pull request merged**
