### PR TITLE
Slashes don't matter

### LINKED ISSUE #21: Add trailing slash to /project route
`@app.route('/<project>')` --> `@app.route('/<project>/')`

Makes the browser add the trailing slash too. Sweet.

### PR DESCRIPTION
**Pull request by taylortrimble**
Whatever the user types is what they get.

Closes #21.

### CODE REVIEW

**Comment by taylortrimble** [comment]
@mplewis, this starts tests. Let me know what you think.

**Comment by mplewis** [comment]
Want to consider finding something in this that works for every route?: http://flask.readthedocs.org/en/0.3/api.html

Cmd-F for `strict_slashes` in that doc. We may be able to disable strict slashes on all paths.

I'm going to email the Flask mailinglist about this.

**Comment by taylortrimble** [comment]
Your foray into the mailing list went well! Here's what you're seeing with strict slashes:

We would expect `app.url_map.strict_slashes = False` to fix our problem. Werkzeug URL map defaults can be overridden by routes, but we aren't specifying `strict_slashes = True` in our Flask routes so problem solved, right?

However, Flask is _naughty_ and assumes that when we don't specify `strict_slashes = False` on our Flask routes that we want it to be `strict_slashes = True` for each route we add. This ends up overriding our `url_map` defaults.

I personally :heart: the decorator idea one of the users on the mailing list had, so I'll implement that ASAP.

**Comment by mplewis** [comment]
I maybe cheated and just moved straight into pushing to the branch again oops.

However, we're on py.test now. The one rule with py.test: When in doubt, prefix it with `test`.

Do a `pip install pytest` then run `py.test` to run tests.

**Comment by mplewis** [comment]
I am also a big fan of the modified decorator. Looking forward to your push.

**Comment by taylortrimble** [comment]
@mplewis Whoop, dey-it-is. Unfortunately, I tested your tests, and I'm either running them wrong or they don't work. :stuck_out_tongue_closed_eyes: Let me know which it is! And then if that works I'll feel comfy merging this.

**Comment by mplewis** [comment]
Logs?

**Comment by taylortrimble** [comment]
> add a comment here to remind us why we did it.

Wat?

> in code or on GH?

The merging you mean? I want to press this button after tests work: 
screen shot 2013-06-19 at 6 08 35 pm

**Comment by mplewis** [comment]
`mplewis commented on 9580418 server_dev.py:L6`

Don't worry about it lol.

I do, however, want to see your `py.test` logs.

**Comment by taylortrimble** [comment]
Oh! Haha, GitHub is fine due to blame/history facility. It will circle back to this Pull Request. No extra work needed.

```
# Currently should fail
(twnet)taylor:teslaworks.net % python test_teslaworks.py 
(twnet)taylor:teslaworks.net % 

# Change code, now it should pass
(twnet)taylor:teslaworks.net % python test_teslaworks.py 
(twnet)taylor:teslaworks.net % 
```

Erry time, for me! Nothing happens.

**Comment by mplewis** [comment]
Don't run `python test_teslaworks.py`, just run `py.test`.

**Comment by taylortrimble** [comment]
Derp. All better. Ready to go?

**Pull request merged**
