### PR TITLE
New FAQs

### LINKED ISSUE #86: FAQ Redo
New FAQ layout:
- Instead of Question and Answer, formatted like:
#### Would you make a good member?

Our group attracts the brightest self-starters and people interested in gaining tons of hands-on experience. Engineers, designers, scientists, and artists especially love our group, but we have members from many other disciplines as well.
#### Wondering how you can help?

The best way to find out is to learn more about the projects. Find a project that interests you, and let the project manager know what looks interesting to you.
#### What about skill level and time commitment?

Any.
#### Can't make the meeting?

That's okay. Most projects meet on their own at other times during the week. Go to a project page to see when.

In fact, I kind of like those FAQs. Loading them up soon, and not doing that bullshit nasty-looking-anyway collapse thing anymore.

### PR DESCRIPTION
**Pull request by taylortrimble**
Redoing the FAQs a la #86.

Closes #86.

### CODE REVIEW

**Comment by taylortrimble** [comment]
Now also addresses #88, and is making me want Bootstrap 3 for better form controls.

**Comment by mplewis** [comment]
Looks like an excellent start. :snake:

**Comment by mplewis** [comment]
(that means do it :dolphin:)

**Comment by taylortrimble** [comment]
Figured! Thx!

**Pull request merged**
