### PR TITLE
Revamp Tumblr theme

### LINKED ISSUE #85: Revisit Tumblr Masthead and Width
The most common place to go back from Tumblr is our home page, so lets have those be the same width (`span8`).

Let's also get rid of the text below it inside the masthead: "Check out the latest news from your favorite student group!" I don't like it, and if you convince me to keep it I'd still want to keep it out of the masthead. :stuck_out_tongue_winking_eye:

### LINKED ISSUE #90: Tumblr pagination
Right now only one post shows up on the landing page on Tumblr. Must phix!

### LINKED ISSUE #108: Tumblr Images
In general, our Tumblr theming needs a _little_ more work. Especially on images though.

Much larger text overall, more centering would be appreciated.

### PR DESCRIPTION
**Pull request by taylortrimble**
This is actually live right now: http://news.teslaworks.net/

Improvements include:
- Matching nav bar (masthead)
- Better (IMO) title link styling
- Better (IMO) date link styling
- Narrower page
- "Polaroid" image styling
- Updates automatically from main site CSS (for general style)

Closes #85 
Closes #90 
Closes #108

### CODE REVIEW

**Comment by mplewis** [comment]
We still need to figure out that left side spacing issue. It doesn't look like it's padding-left, margin-left, or text-indent.

**Comment by taylortrimble** [comment]
Okay, figured it out - good catch! What do you think now?

**Comment by mplewis** [comment]
I really like justified paragraphs. That's at your discretion.

screen shot 2013-11-05 at 5 25 00 pm

Otherwise it looks great!

**Comment by taylortrimble** [comment]
For the tumbleblogz I think justification would be great. I'll add it in!

**Comment by taylortrimble** [comment]
Okay, merging! (this is out in the wild already anyway)

**Pull request merged**
