### PR TITLE
Add another MailChimp form to the homepage

### PR DESCRIPTION
**Pull request by mplewis**
Matt wants more subscriptions. Here's how Matt wants them.

screen shot 2013-11-15 at 1 07 30 pm

Also change the caps on `Mailing List` to `mailing list!`

### CODE REVIEW

**Comment by mplewis** [comment]
Pull at will, @tylrtrmbl. Or argue about things :D

**Comment by kevana** [comment]
I like it. I am also not @tylrtrmbl :neutral_face:

**Comment by taylortrimble** [comment]
I like it too! Do you like what I did with #179?

**Comment by mplewis** [comment]
Yep! If it looks good to you, pull at will.

**Comment by taylortrimble** [comment]
Shipped!

**Pull request merged**
